### ISSUE TITLE
Would you please give more details on the synthesis of deformed sketch?

### ISSUE THREAD

**Issue by cnnlstm** [LiYuhangUSTC/Sketch2Face#1]
Thanks for your amazing work, would you please give more details on the synthesis of the deformed sketch? Or will you release the deformed sketch in the future?

**Comment by LiYuhangUSTC** [comment]
1. Use AutoTrace to get the vectorized form of each curve in a sketch, e.g. a list of 2D coordinates of end points and control points for each curve. (Knowledge about spline curves required)
2. Add a random value to each coordinate, geting a new list for each curve.
3. Save all new curves as .svg file. (Knowledge about .svg file required)
4. Use cairosvg (Python) to convert .svg to .png

**Comment by cnnlstm** [comment]
Thanks for your detailed reply！

**Comment by LiYuhangUSTC** [comment]
I added util/sketch_process.py which is used to vectorize sketch using AutoTrace and adding random offsets. This tool is not fully tested. It will be appreciated if you try it and feedback.

**Comment by BenfenYU** [comment]
Hi,
I have tried util/sketch_process.py, and I got nothing in my *.svg.
The bmp sketch I put in is 
![image](https://user-images.githubusercontent.com/33017944/96677018-4a2c1f00-13a1-11eb-9f65-7fd195cd3ad3.png)
The output is
![image](https://user-images.githubusercontent.com/33017944/96677050-5d3eef00-13a1-11eb-942d-33fce417beed.png)
