### ISSUE TITLE
Error in testing code

### ISSUE THREAD

**Issue by VarV0id** [LiYuhangUSTC/Sketch2Face#2]
Hello. First of all, thanks for your awesome work. 

I was trying to test the network to generate a face from a sketch, I have installed all the requirements, but when i run the command, it shows me the following error:
![imagen](https://user-images.githubusercontent.com/26202574/97095611-427dac00-1627-11eb-99cc-efec8f5fb24c.png)
I have find that the problem is in this sector.
![imagen](https://user-images.githubusercontent.com/26202574/97095698-62619f80-1628-11eb-91f2-19eba7fd3a02.png)

How can i resolve it?

Thank you so much.

**Comment by LiYuhangUSTC** [comment]
Seems you have not downloaded the pre-trained models or not placed them in the right folder.

**Comment by VarV0id** [comment]
I have downloaded all the pretrained files, but the deform.pth is missing. The other pretrained models work well.

**Comment by hendshaker** [comment]
Hello, thanks for your awesome work.
i have downloaded all the pretrained files, but the deform.pth is missing.
i want you to help us in our GP.

**Comment by LiYuhangUSTC** [comment]
Sorry so much for replying so late. I have left USTC and do not check the USTC email and github repo frequently. The file deform.pth is uploaded to GoogleDrive along with the other model files.

**Comment by LiYuhangUSTC** [comment]
The deform.pth file is uploaded to google drive. Please check it out.

在2021-02-03 01:49:50，hendshakernotifications@github.com写道：

Hello, thanks for your awesome work.
i have downloaded all the pretrained files, but the deform.pth is missing.
i want you to help us in our GP.
